 id | author_id |                     header                      |                                                                                 text_post                                                                                  |         created_at         
----+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------
  1 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:30:24.330936
  2 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:30:29.480938
  3 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:30:31.278586
  4 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:30:32.614969
  5 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:30:35.312904
  6 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:31:10.891747
  7 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:36:18.833652
  8 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:47:44.732563
  9 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:54:14.038555
 10 |         5 | ебу блять собак нахуй и котов сука автор гандон | блять говно нахуй Parse parses a formatted string and returns the time value it represents. The layout defines the format by showing how the reference time, defined to be | 2021-02-05 23:54:16.625567
 11 |         5 | hellobleat                                      | hehehehehe                                                                                                                                                                 | 2021-02-18 20:11:31.549521
 12 |         5 | hellobleat                                      | hehehehehe                                                                                                                                                                 | 2021-02-18 20:11:34.892185
 13 |         5 | ddddddddddd                                     | dsadasdasdgvsd                                                                                                                                                             | 2021-02-18 20:50:09.284614
 14 |         5 | hellobleat                                      | heheheheheh                                                                                                                                                                | 2021-02-18 21:02:38.853205
 15 |         5 | hellobleat                                      | heheheheheh                                                                                                                                                                | 2021-02-18 21:03:29.720312
(15 rows)

